//CONSULTAS A LA DB
export const CONSULTA_PAISES = "CONSULTA_PAISES"; //--> USADA 
export const CONSULTA_PAIS_ID = "CONSULTA_PAIS_ID"; //--> USADA 
export const CONSULTA_PAIS_NAME = "CONSULTA_PAIS_NAME"; //--> USADA
export const CONSULTA_CONTINENTS = "CONSULTA_CONTINENTS"; //--> USADA


export const LIMPIAR_PAIS = "LIMPIAR_PAIS"; //--> NO USADA


//FILTROS Y ORDENAMIENTO
export const ORDEN_ALFABETICO_PAISES = "ORDEN_ALFABETICO_PAISES" //--> USADA
export const ORDEN_HABITANTES_PAISES = "ORDEN_HABITANTES_PAISES" //--> USADA
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT" //--> USADA
export const FILTER_BY_ACTIVITIE = "FILTER_BY_ACTIVITIE" //--> USADA
export const CONSULTA_ACTIVITIES = "CONSULTA_ACTIVITIES" //--> USADA
export const SET_FILTERED_COUNTRIES = "SET_FILTERED_COUNTRIES" //--> USADA
